#+title: Daily work log for Harsha Vattem

* Month of May
** [2016-05-16 Mon]
   I learnt basic skills about operating the terminal, git and emacs. Using these, I was able to create repositories and also operate with remote repositories.

** [2016-05-17 Tue]
   I learnt about data modelling, and its importance to the building of any application. I also learnt about relations, cardinality and entities, and used them to create a data model based upon the one shown in class.

** [2016-05-18 Wed]
   I was given an introduction to Object Oriented Programming in Python. We were give a template on which we were to implement the data models we had built on Tuesday. I spent a lot of the day familiarising myself with the idea of Object Oriented Programming.

** [2016-05-19 Thu]
   We continued building methods and test cases using the given template from yesterday. A few doubts of yesterday were set right, and we came close to completion. I am also getting better at handling Python and Object Oriented programming in general.

** [2016-05-20 Fri]
   I finally got the confidence to build the program, not just learn. I started writing methods and understanding the format of test cases. 
   

** Weekly  Summary
   I learnt a lot this week, from the basics of git and emacs to OOP in Python, and I am now able to write my own program in Python, albeit with errors.
   
** [2016-05-23 Mon]
   I have started reading up on AngularJS and how to use it to write a basic interactive application for the client side interface.
   
** [2016-05-24 Tue]
   I have been introduced to MySQLAlchemy and how to use databases, and I have been preparing the ORM from the template provided. The previous Python program is being used as a reference.
   
** [2016-05-25 Wed]
   I learnt a bit about the RestAPI and the Get, Push, Post commands using the HTTP Requester plugin. I also saw the working of the final program.
   
** [2016-05-26 Thu]
   The day was spent in editing the previous template. We are getting closer to building the final ORM model.
   
** [2016-05-27 Fri]
   We are to start with building the client side of the web application soon. I learnt a little bit about how HTML, CSS, JavaScript are used to create interactive, dynamic web pages.
   
** Weekly Summary
   We have been building the RestAPI and making test cases in it. The definition and making of a web application is becoming clear to me, as is the sturucture of an application. 
   
** [2016-05-30 Mon]
   Most of the day was spent trying to fix an issue while running the API. I also read up on JavaScript a little bit, anticipating the upcoming project. 
   
** [2016-05-31 Tue]
   In the morning, a few groups displayed their work, but most of it was incomplete. We ended fixing an issue that had been giving us problems, and started working on making the front end.

* Month of June
   
** [2016-06-01 Wed]
   We had a little bit of success with the front end, but a few errors kept popping up. The interface is working, but we are facing a few issues with some functions. I have also started the documentation. 
   
** [2016-06-02 Thu]
   We have started the deployment. I am facing some issues, probably because my name is not actually in this group. However, I have part of it up. I shall also have finished the documentation by the end of the day.
   
** [2016-06-03 Fri]
   Deployment was completes, and with that, making of the web application was done. We also demonstrated our respective teams' apps. Later, we interacted with Prof. Viswanath, who briefed us about Discrete Dynamic Systems.
   
** Weekly Summary
   We learnt a little but about AngularJS, and creating the front end of a web application using it. We learnt about and created virtual machines also.
   
** [2016-06-06 Mon]
   We had learnt a little bit about JavaScript's p5 framework. We are to apply ths framework for interactive/animated objects. We thus read about the framework and its syntax and started making a distance-time graph taking user inputs.
   
** [2016-06-07 Tue]
   The distance-time graph we had started on yesterday continued. We spent time smoothening issues in the program. We showed it to Prof. Venkatesh in the afternoon, and he told us to get three examples of infinite iteration ready by next week.
   
** [2016-06-08 Wed]
   We started working on our programs today. We are trying to implement the few ideas we are getting. One program is involving a simple word game =Atlas= , which we have almost been able to complete.

** [2016-06-09 Thu]
   We completed the game we were working on yesterday, and have started another simple program of four persons throwing a ball randomly throwing a ball to each other. However, animating it is turning out to be a problem.

** [2016-06-10 Fri]
   The simple ball game is complete, with no beautification though. That can probably be done over the weekend. We have a few other programs half done, but are unsure which one to complete because of a little confusion over the logic. We shall work over the weekend a bit to get them done and the earlier ones to look better.
   
** Weekly Summary
   We learnt some theory about Discrete Dynamics, and Iteration. We also have started working with the p5 JS framework, which is making our task much easier.
   
** [2016-06-13 Mon] 
   We finished a traffic light application today. In addition, Prof. Venkatesh talked to us a bit about the applications, and how to formulate input and output in Discrete Dynamis Systems.

** [2016-06-14 Tue]
   We have made plots of our applications, such that they show they history of the process. We are also experimenting with CSS, to make the page look better.
   
** [2016-06-15 Wed]
   Tried to fix a problem in the plot of the traffic light application: the plot was timed and coloured wrong. We have also started to cunstruct the application into a consistent paneled interface, as Professor Venkatesh has advised.
   
** [2016-06-16 Thu] 
   Having gotten the applications right, we have been flattening small problems with bounday cases and some details we have overlooked. Additionally, we are using various p5 and CSS features to enhance the appearance of the applications.
   
** [2016-06-17 Fri] 
   We met Professor Venkatesh today, and presented our applications to him. We initiated the idea of having a framework to build discrete dynamic systems with minimal input. As a side interest, we have also experimented with a few interesting JS libraries, like plotly.js.
   
** Weekly Summary
   We are now able to effectively use p5 and make applications both functional and attractive. We have also improved our understanding of infinite iteration.
   
** [2016-06-20 Mon] 
   Now, we have taken on another project: to try and derive a framework to convert Flash animations to JavaScript, to convert all the Virtual Labs on the website. This shall be our focus now.
   
** [2016-06-21 Tue] 
   I have been searching online for tools which could possibly simplify the function of the conversion. I have found a few online tools which claim to do the entire conversion, but I am unable to get them to work.
   
** [2016-06-22 Wed]
   We have tried out a software called Google Web Designer, as it might have helped us generate the code we need and could be the simple method we were looking for. It generates codes for graphic animations that can be easily made. 
   
** [2016-06-23 Thu] 
   Google Web Designer, being a Beta version, is not perfect. In addition, itdoes not have a lot of the features we need. In addition, we are considering other methods, and we tried referring to a fellow teammate's project to get some ideas.
   
** [2016-06-24 Fri] 
   In today's meeting, our mission underwent a slight change. We are now to convert a single experiment to JS, trying a few different methods, documenting the process. This might help develop the automation we were working on earlier.
   
** Weekly Summary
   We spent time searching online for tools, and then libraries and other methods to help us in our task. Because of the project having been changed, we are not close to completion.
   
** [2016-06-27 Mon] 
   We are analyzing a project which has been converted to JS without using any tools or frameworks. Understanding this will help us find out parts we can simplify or make more effective by using other methods.
   
** [2016-06-28 Tue] 
   We are unable to deconstruct the elements of the existing Flash projectss in our laptops, so we are yet to find a way to do so. We need these elements if we want to build an exact replica of the lab.
   
** [2016-06-29 Wed] 
   We tried looking for frameworks which would effectively animate labs the same way as Flash. Hovewer, most animation libraries involve overly creative special effects which are not what we are looking for. Some parts of the existing code might be reusable, and we are considering building on that. 
   
** [2016-06-30 Thu]
   

   
* Month of July  
   
** [2016-07-01 Fri]   
   
   
** Weekly Summary
   
   
** [2016-07-04 Mon]
   
** [2016-07-05 Tue]
   
** [2016-07-06 Wed]
   
** [2016-07-07 Thu]
   
** [2016-07-08 Fri]

** Weekly Summary
   
** [2016-07-11 Mon]
   
** [2016-07-12 Tue]
   
** [2016-07-13 Wed]
   
** [2016-07-14 Thu]
   
** [2016-07-15 Fri]
   
