#+title: Daily work log for Harsha Vattem

* Month of May
** [2016-05-16 Mon]
   I learnt basic skills about operating the terminal, git and emacs. Using these, I was able to create repositories and also operate with remote repositories.

** [2016-05-17 Tue]
   I learnt about data modelling, and its importance to the building of any application. I also learnt about relations, cardinality and entities, and used them to create a data model based upon the one shown in class.

** [2016-05-18 Wed]
   I was given an introduction to Object Oriented Programming in Python. We were give a template on which we were to implement the data models we had built on Tuesday. I spent a lot of the day familiarising myself with the idea of Object Oriented Programming.

** [2016-05-19 Thu]
   We continued building methods and test cases using the given template from yesterday. A few doubts of yesterday were set right, and we came close to completion. I am also getting better at handling Python and Object Oriented programming in general.

** [2016-05-20 Fri]
   I finally got the confidence to build the program, not just learn. I started writing methods and understanding the format of test cases. 
   

** Weekly  Summary
   I learnt a lot this week, from the basics of git and emacs to OOP in Python, and I am now able to write my own program in Python, albeit with errors.
   
** [2016-05-23 Mon]
   I have started reading up on AngularJS and how to use it to write a basic interactive application for the client side interface.
   
** [2016-05-24 Tue]
   I have been introduced to MySQLAlchemy and how to use databases, and I have been preparing the ORM from the template provided. The previous Python program is being used as a reference.
   
** [2016-05-25 Wed]
   I learnt a bit about the RestAPI and the Get, Push, Post commands using the HTTP Requester plugin. I also saw the working of the final program.
   
** [2016-05-26 Thu]
   The day was spent in editing the previous template. We are getting closer to building the final ORM model.
   
** [2016-05-27 Fri]
   We are to start with building the client side of the web application soon. I learnt a little bit about how HTML, CSS, JavaScript are used to create interactive, dynamic web pages.
   
** Weekly Summary
   We have been building the RestAPI and making test cases in it. The definition and making of a web application is becoming clear to me, as is the sturucture of an application. 
   
** [2016-05-30 Mon]
   Most of the day was spent trying to fix an issue while running the API. I also read up on JavaScript a little bit, anticipating the upcoming project. 
   
** [2016-05-31 Tue]
   In the morning, a few groups displayed their work, but most of it was incomplete. We ended fixing an issue that had been giving us problems, and started working on making the front end.

* Month of June
   
** [2016-06-01 Wed]
   We had a little bit of success with the front end, but a few errors kept popping up. The interface is working, but we are facing a few issues with some functions. I have also started the documentation. 
   
** [2016-06-02 Thu]
   We have started the deployment. I am facing some issues, probably because my name is not actually in this group. However, I have part of it up. I shall also have finished the documentation by the end of the day.
   
** [2016-06-03 Fri]
   Deployment was completes, and with that, making of the web application was done. We also demonstrated our respective teams' apps. Later, we interacted with Prof. Viswanath, who briefed us about Discrete Dynamic Systems.
   
** Weekly Summary
   We learnt a little but about AngularJS, and creating the front end of a web application using it. We learnt about and created virtual machines also.
   
** [2016-06-06 Mon]
   We had learnt a little bit about JavaScript's p5 framework. We are to apply ths framework for interactive/animated objects. We thus read about the framework and its syntax and started making a distance-time graph taking user inputs.
   
** [2016-06-07 Tue]
   The distance-time graph we had started on yesterday continued. We spent time smoothening issues in the program. We showed it to Prof. Venkatesh in the afternoon, and he told us to get three examples of infinite iteration ready by next week.
   
** [2016-06-08 Wed]
   We started working on our programs today. We are trying to implement the few ideas we are getting. One program is involving a simple word game =Atlas= , which we have almost been able to complete.

** [2016-06-09 Thu]
   We completed the game we were working on yesterday, and have started another simple program of four persons throwing a ball randomly throwing a ball to each other. However, animating it is turning out to be a problem.

** [2016-06-10 Fri]
   The simple ball game is complete, with no beautification though. That can probably be done over the weekend. We have a few other programs half done, but are unsure which one to complete because of a little confusion over the logic. We shall work over the weekend a bit to get them done and the earlier ones to look better.
   
** Weekly Summary
   We learnt some theory about Discrete Dynamics, and Iteration. We also have started working with the p5 JS framework, which is making our task much easier.
 
* Month of July
