#+title: Daily work log for Harsha Vattem

* Month of May
** [2016-05-16 Mon]
   I learnt basic skills about operating the terminal, git and emacs. Using these, I was able to create repositories and also operate with remote repositories.

** [2016-05-17 Tue]
   I learnt about data modelling, and its importance to the building of any application. I also learnt about relations, cardinality and entities, and used them to create a data model based upon the one shown in class.

** [2016-05-18 Wed]
   I was given an introduction to Object Oriented Programming in Python. We were give a template on which we were to implement the data models we had built on Tuesday. I spent a lot of the day familiarising myself with the idea of Object Oriented Programming.

** [2016-05-19 Thu]
   We continued building methods and test cases using the given template from yesterday. A few doubts of yesterday were set right, and we came close to completion. I am also getting better at handling Python and Object Oriented programming in general.

** [2016-05-20 Fri]
   I finally got the confidence to build the program, not just learn. I started writing methods and understanding the format of test cases. 
   

** Weekly  Summary
   I learnt a lot this week, from the basics of git and emacs to OOP in Python, and I am now able to write my own program in Python, albeit with errors.
   
** [2016-05-23 Mon]
   I have started reading up on AngularJS and how to use it to write a basic interactive application for the client side interface.
   
** [2016-05-24 Tue]
   I have been introduced to MySQLAlchemy and how to use databases, and I have been preparing the ORM from the template provided. The previous Python program is being used as a reference.
   
** [2016-05-25 Wed]
   I learnt a bit about the RestAPI and the Get, Push, Post commands using the HTTP Requester plugin. I also saw the working of the final program.
   
** [2016-05-26 Thu]
   The day was spent in editing the previous template. We are getting closer to building the final ORM model.
   
** [2016-05-27 Fri]
   We are to start with building the client side of the web application soon. I learnt a little bit about how HTML, CSS, JavaScript are used to create interactive, dynamic web pages.
   
** Weekly Summary
   We have been building the RestAPI and making test cases in it. The definition and making of a web application is becoming clear to me, as is the sturucture of an application. 
   
** [2016-05-30 Mon]
   Most of the day was spent trying to fix an issue while running the API. I also read up on JavaScript a little bit, anticipating the upcoming project. 
   
** [2016-05-31 Tue]
   In the morning, a few groups displayed their work, but most of it was incomplete. We ended fixing an issue that had been giving us problems, and started working on making the front end.
   
** [2016-06-01 Wed]
   We had a little bit of success with the front end, but a few errors kept popping up. The interface is working, but we are facing a few issues with some functions. I have also started the documentation.
   
** [2016-06-02 Thu]
   We have started the deployment. I am facing some issues, probably because my name is not actually in this group. However, I have part of it up. I shall also have finished the documentation by the end of the day.
   
   
* Month of June
* Month of July
