#+title: Daily work log for Harsha Vattem

* Month of May
** [2016-05-16 Mon]
   I learnt basic skills about operating the terminal, git and emacs. Using these, I was able to create repositories and also operate with remote repositories.

** [2016-05-17 Tue]
   I learnt about data modelling, and its importance to the building of any application. I also learnt about relations, cardinality and entities, and used them to create a data model based upon the one shown in class.

** [2016-05-18 Wed]
   I was given an introduction to Object Oriented Programming in Python. We were give a template on which we were to implement the data models we had built on Tuesday. I spent a lot of the day familiarising myself with the idea of Object Oriented Programming.

** [2016-05-19 Thu]
   We continued building methods and test cases using the given template from yesterday. A few doubts of yesterday were set right, and we came close to completion. I am also getting better at handling Python and Object Oriented programming in general.

** [2016-05-20 Fri]
   I finally got the confidence to build the program, not just learn. I started writing methods and understanding the format of test cases. 
   

** Weekly  Summary
   I learnt a lot this week, from the basics of git and emacs to OOP in Python, and I am now able to write my own program in Python, albeit with errors.
   
** [2016-05-23 Mon]
   I have started reading up on AngularJS and how to use it to write a basic interactive application for the client side interface. I can make basic Input/Output web pages using JavaScript now.
   
** [2016-05-24 Tue]
   I have been introduced to MySQLAlchemy and how to use databases, and I have been preparing the ORM from the template provided. The previous Python program is being used as a reference.
   
* Month of June
* Month of July
